name: Rolling - Debian Semi-Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/rolling-debian-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'topic_based_hardware_interfaces.rolling.repos'
      - 'topic_based_hardware_interfaces.kilted.repos'
      - 'topic_based_hardware_interfaces.jazzy.repos'
      - '**.xml'
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '33 2 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  debian_semi_binary_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted, rolling]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      upstream_workspace: topic_based_hardware_interfaces.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: main
