name: Rolling - ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/rolling-abi-compatibility.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'topic_based_hardware_interfaces.rolling.repos'
      - 'topic_based_hardware_interfaces.kilted.repos'
      - 'topic_based_hardware_interfaces.jazzy.repos'
      - '**.xml'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  abi_check:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted, rolling]
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-abi-check.yml@master
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
