name: Rolling - Coverage Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/rolling-coverage-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'topic_based_hardware_interfaces.rolling.repos'
      - '**.xml'
  pull_request:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/rolling-coverage-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'topic_based_hardware_interfaces.rolling.repos'
      - '**.xml'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  coverage_rolling:
    name: coverage build - rolling
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: rolling
